#!/usr/bin/env python3
"""
Generate embedded_assets.c/h from assets/ directory.
Embeds all required asset files as C arrays for standalone restool binary.
"""

import os
import sys

# Asset patterns to embed (relative to assets/)
ASSET_PATTERNS = [
    # Dungeon YAML files
    ("dungeon/dungeon-*.yaml", True),
    ("dungeon/default_rooms.yaml", False),
    ("dungeon/overlay_rooms.yaml", False),
    # Overworld YAML files
    ("overworld/overworld-*.yaml", True),
    # Music/sound text files
    ("sound_intro.txt", False),
    ("sound_indoor.txt", False),
    ("sound_ending.txt", False),
    ("sfx.txt", False),
    ("music_info.yaml", False),
    # BRR audio samples
    ("sound/*.brr", True),
    # Text data
    ("dialogue.txt", False),
    ("map32_to_map16.txt", False),
    # PNG images
    ("linksprite.png", False),
    ("font.png", False),
    ("font_*.png", True),
    ("hud_icons.png", False),
]

def find_files(assets_dir):
    """Find all asset files to embed."""
    import fnmatch
    files = []

    for pattern, is_glob in ASSET_PATTERNS:
        if is_glob:
            # Handle wildcard patterns
            base_pattern = pattern
            if '/' in pattern:
                subdir, base_pattern = pattern.rsplit('/', 1)
                search_dir = os.path.join(assets_dir, subdir)
            else:
                search_dir = assets_dir

            if os.path.isdir(search_dir):
                for filename in sorted(os.listdir(search_dir)):
                    if fnmatch.fnmatch(filename, base_pattern):
                        if '/' in pattern:
                            rel_path = f"{subdir}/{filename}"
                        else:
                            rel_path = filename
                        full_path = os.path.join(assets_dir, rel_path)
                        if os.path.isfile(full_path):
                            files.append((rel_path, full_path))
        else:
            # Direct file path
            full_path = os.path.join(assets_dir, pattern)
            if os.path.isfile(full_path):
                files.append((pattern, full_path))

    return files

def sanitize_name(path):
    """Convert path to valid C identifier."""
    name = path.replace('/', '_').replace('.', '_').replace('-', '_')
    return f"asset_{name}"

def generate_c_array(data, name):
    """Generate C array declaration for binary data."""
    lines = [f"static const uint8_t {name}[] = {{"]

    # Format as hex bytes, 16 per line
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        hex_bytes = ", ".join(f"0x{b:02x}" for b in chunk)
        if i + 16 < len(data):
            hex_bytes += ","
        lines.append(f"    {hex_bytes}")

    lines.append("};")
    return "\n".join(lines)

def main():
    if len(sys.argv) != 4:
        print(f"Usage: {sys.argv[0]} <assets_dir> <output.c> <output.h>")
        sys.exit(1)

    assets_dir = sys.argv[1]
    output_c = sys.argv[2]
    output_h = sys.argv[3]

    if not os.path.isdir(assets_dir):
        print(f"Error: Assets directory not found: {assets_dir}")
        sys.exit(1)

    files = find_files(assets_dir)
    print(f"Found {len(files)} asset files to embed")

    # Generate header file
    with open(output_h, 'w') as f:
        f.write("// Auto-generated by generate_embedded_assets.py - DO NOT EDIT\n")
        f.write("#ifndef EMBEDDED_ASSETS_H\n")
        f.write("#define EMBEDDED_ASSETS_H\n\n")
        f.write("#include <stdint.h>\n")
        f.write("#include <stddef.h>\n\n")
        f.write("typedef struct {\n")
        f.write("    const char *name;\n")
        f.write("    const uint8_t *data;\n")
        f.write("    size_t size;\n")
        f.write("} EmbeddedAsset;\n\n")
        f.write("// Get embedded asset by path (e.g., \"dungeon/dungeon-0.yaml\")\n")
        f.write("// Returns NULL if not found\n")
        f.write("const EmbeddedAsset* EmbeddedAssets_Find(const char *path);\n\n")
        f.write("// Get asset data directly, returns NULL if not found\n")
        f.write("const uint8_t* EmbeddedAssets_GetData(const char *path, size_t *out_size);\n\n")
        f.write(f"#define EMBEDDED_ASSETS_COUNT {len(files)}\n\n")
        f.write("#endif // EMBEDDED_ASSETS_H\n")

    # Generate source file
    total_size = 0
    with open(output_c, 'w') as f:
        f.write("// Auto-generated by generate_embedded_assets.py - DO NOT EDIT\n")
        f.write("#include \"embedded_assets.h\"\n")
        f.write("#include <string.h>\n\n")

        # Write all data arrays
        for rel_path, full_path in files:
            with open(full_path, 'rb') as asset_file:
                data = asset_file.read()

            name = sanitize_name(rel_path)
            f.write(f"// {rel_path} ({len(data)} bytes)\n")
            f.write(generate_c_array(data, name))
            f.write("\n\n")
            total_size += len(data)

        # Write asset table
        f.write("// Asset lookup table\n")
        if files:
            f.write("static const EmbeddedAsset kEmbeddedAssets[] = {\n")
            for rel_path, full_path in files:
                name = sanitize_name(rel_path)
                size = os.path.getsize(full_path)
                # Normalize path separators
                norm_path = rel_path.replace('\\', '/')
                f.write(f'    {{"{norm_path}", {name}, sizeof({name})}},\n')
            f.write("};\n\n")
        else:
            # Empty assets - use NULL pointer instead of zero-size array
            f.write("static const EmbeddedAsset *kEmbeddedAssets = NULL;\n\n")

        # Write lookup function
        f.write("const EmbeddedAsset* EmbeddedAssets_Find(const char *path) {\n")
        f.write("    if (!path) return NULL;\n")
        if files:
            f.write("    // Skip leading \"assets/\" if present\n")
            f.write("    if (strncmp(path, \"assets/\", 7) == 0) path += 7;\n")
            f.write(f"    for (int i = 0; i < {len(files)}; i++) {{\n")
            f.write("        if (strcmp(kEmbeddedAssets[i].name, path) == 0) {\n")
            f.write("            return &kEmbeddedAssets[i];\n")
            f.write("        }\n")
            f.write("    }\n")
        else:
            f.write("    (void)path; // No embedded assets available\n")
        f.write("    return NULL;\n")
        f.write("}\n\n")

        f.write("const uint8_t* EmbeddedAssets_GetData(const char *path, size_t *out_size) {\n")
        f.write("    const EmbeddedAsset *asset = EmbeddedAssets_Find(path);\n")
        f.write("    if (!asset) return NULL;\n")
        f.write("    if (out_size) *out_size = asset->size;\n")
        f.write("    return asset->data;\n")
        f.write("}\n")

    print(f"Generated {output_c} and {output_h}")
    print(f"Total embedded data: {total_size:,} bytes ({total_size/1024/1024:.1f} MB)")

if __name__ == "__main__":
    main()
